services:
  - type: web
    name: biblioteca-app
    runtime: python
    buildCommand: pip install -r biblioteca/requirements.txt
    startCommand: gunicorn biblioteca.app:create_app()
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
